inherit_from: .rubocop_todo.yml

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise
