dist: trusty
cache: bundler
sudo: false

language: ruby
rvm:
- 2.6.3

addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

services:
- memcached

before_script:
- script/travis_prepare
