dist: focal

cache:
  bundler: true
  yarn: true

language: ruby

rvm:
- 2.7.1

services:
- memcached
- postgresql

addons:
  postgresql: 12

before_script:
- nvm use 12
- yarn install
- script/travis_prepare
